void bogoSort(int arr[], int cols, int rows);
void bubbleSort(int arr[], int cols, int rows);
void quickSort(int arr[], int low, int high, int cols, int rows);
void shellSort(int arr[], int cols, int rows);
void mergeSort(int arr[], int low, int high, int cols, int rows);
void heapSort(int arr[], int cols, int rows);
void gnomeSort(int arr[], int cols, int rows);
void cocktailSort(int arr[], int cols, int rows);
void insertionSort(int arr[], int cols, int rows);
void selectionSort(int arr[], int cols, int rows);
void oddevenSort(int arr[], int cols, int rows);
void pancakeSort(int arr[], int cols, int rows);
void pigeonholeSort(int arr[], int cols, int rows);
void combSort(int arr[], int cols, int rows);
void stoogeSort(int arr[], int low, int high, int cols, int rows);
