struct Counter bogoSort(int arr[], int n);
struct Counter bubbleSort(int arr[], int n);
struct Counter quickSortWrapper(int arr[], int n);
struct Counter shellSort(int arr[], int n);
struct Counter mergeSort(int arr[], int low, int high, int n);
struct Counter heapSort(int arr[], int n);
struct Counter gnomeSort(int arr[], int n);
struct Counter cocktailSort(int arr[], int n);
struct Counter insertionSort(int arr[], int n);
struct Counter selectionSort(int arr[], int n);
struct Counter oddevenSort(int arr[], int n);
struct Counter pancakeSort(int arr[], int n);
struct Counter pigeonholeSort(int arr[], int n);
struct Counter combSort(int arr[], int n);
struct Counter stoogeSort(int arr[], int low, int high, int n);
struct Counter badSortWrapper(int arr[], int n);
struct Counter dropSort(int arr[], int n);
struct Counter radixSort(int arr[], int n);
struct Counter bozoSort(int arr[], int n);
struct Counter inplaceMergeSortWrapper(int arr[], int n);
